### ISSUE TITLE
Style of About Us Page

### ISSUE THREAD

**Issue by Louis-He** [UTACE/ACEKnow#33]
The "About us" page seems to have too much margin space between sections.

**Comment by Louis-He** [comment]
Also, all the images on the page should be local instead of linking to another website.

**Comment by CatherineZM** [comment]
@AmilyWu @Ethan-Haodong-Ma Can you help take care of this issue, please?

**Comment by Louis-He** [comment]
Font should not adjust based on the size of the screen.
